quarkus:
  application:
    name: painel-investimentos
  
  http:
    port: 8081
    
  datasource:
    db-kind: h2
    jdbc:
      url: jdbc:h2:mem:investimentos;DB_CLOSE_DELAY=-1
      
  hibernate-orm:
    database:
      generation: drop-and-create
    sql-load-script: data.sql
    log:
      sql: true
      format-sql: true
      
  smallrye-health:
    ui:
      enable: true
      
  smallrye-openapi:
    path: /openapi
    info-title: Painel de Investimentos API
    info-version: 1.0.0
    info-description: API REST para análise de perfil de risco e simulação de investimentos
    
  swagger-ui:
    path: /swagger-ui/
    always-include: true
    enable: true
    
mp:
  jwt:
    verify:
      publickey:
        location: /META-INF/resources/publicKey.pem
      issuer: https://caixa.com.br/issuer
    
jwt:
  secret: ${JWT_SECRET:5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437}
  expiration: 86400000 # 24 hours in milliseconds
    
quarkus:
  log:
    level: INFO
    category:
      "com.caixa.invest":
        level: DEBUG
